Controllers/CondicionaisController.cs
using Microsoft.AspNetCore.Mvc;
using Exercicios.Models;

namespace Exercicios.Controllers
{
    public class CondicionaisController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult CondicionalIf()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CondicionalIf(Partida partida)
        {
            return View(partida);
        }

        [HttpGet]
        public IActionResult CondicionalSwitch()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CondicionalSwitch(Pedido pedido)
        {
            return View(pedido);
        }
        
    }
}

Controllers/MatematicosController.cs
using Microsoft.AspNetCore.Mvc;
using Exercicios.Models;

namespace Exercicios.Controllers
{
    public class MatematicosController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Exercicio1()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Exercicio1(string Nome,double Nota1,double Nota2,double Nota3)
        {
            double media = (Nota1 + Nota2 + Nota3)/3.0;
            ViewData["Resultado"] = $"O Aluno {Nome} obteve média {media:N2}";
            return View();
        }

        [HttpGet]
        public IActionResult Exercicio2()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Exercicio2(Prestacao prestacao)
	{
		return View(prestacao);
	}
        
        [HttpGet]
        public IActionResult Exercicio3()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Exercicio3(DolarEmReal dolarEmReal)
        {
		return View(dolarEmReal);
        }

        

    }
}

Controllers/RepeticaoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Exercicios.Models;

namespace Exercicios.Controllers
{
    public class RepeticaoController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public IActionResult RepeticaoWhile()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RepeticaoWhile(Tabuada tabuada)
        {
            tabuada.Tipo = TipoOperador.While;
            tabuada.Calcular();
            return View(tabuada);
        }

        [HttpGet]
        public IActionResult RepeticaoFor()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RepeticaoFor(Tabuada tabuada)
        {
            tabuada.Tipo = TipoOperador.For;
            tabuada.Calcular();
            return View(tabuada);
        }


        [HttpGet]
        public IActionResult RepeticaoDo()
        {
            return View();
        }

        [HttpPost]
        public IActionResult RepeticaoDo(Tabuada tabuada)
        {
            tabuada.Tipo = TipoOperador.Repeat;
            tabuada.Calcular();
            return View(tabuada);
        }
    }
}

Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Exercícios | @ViewData["Title"]</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <link rel="stylesheet" href="~/css/site.css" />
</head> 

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light text-bg-dark box-shadow pb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-controller="Home" asp-action="Index">Exercícios</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse"
                    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon text-white"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="SobreMim">Sobre
                                Mim</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Matematicos"
                                asp-action="Index">Operadores Matemáticos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Condicionais"
                                asp-action="Index">Estruturas Condicionais</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="" asp-controller="Repeticao"
                                asp-action="Index">Estruturas de Repetição</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>

    <main role="main" class="pb-3">
        @RenderBody()
    </main>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa"
        crossorigin="anonymous"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>